name: "FRP Client"
description: "You can use this tool to achieve remote access to local Home Assistant OS by port forwarding"
version: "1.2.0"
slug: "frp_client"
host_network: true
startup: application
boot: "auto"
init: false
map:
  - "share:rw"
privileged:
  - NET_ADMIN
devices:
  - /dev/net/tun
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  serverAddr: "example.com"
  serverPort: 7000
  customDomain: "example.com"
  proxyName: "homeassistant"
  sshProxyName: "ssh"
  sshDeviceName: "ssh-device"
  httpUser: "admin"
  httpPassword: "password"
  locationPath: "/location"
schema:
  serverAddr: str
  serverPort: int
  customDomain: str
  proxyName: str
  sshProxyName: str
  sshDeviceName: str
  httpUser: str
  httpPassword: str
  locationPath: str
