serverAddr = "your_server_addr"
serverPort = 7000

log.to = "/share/frpc.log"
# trace, debug, info, warn, error
log.level = "trace"
log.maxDays = 3

[[proxies]]
name = "your_ssh_proxy_name"
type = "tcpmux"
multiplexer = "httpconnect"
customDomains = ["ssh_device_name"]
localIP = "0.0.0.0"
localPort = 22

[[proxies]]
name = "your_home_assistant_proxy_name"
type = "http"
localPort = 8123
customDomains = ["example.com"]
locations = ["/location"]
httpUser = "http_user" 
httpPassword = "http_password"
