bindPort = 7000
vhostHTTPPort = 8123

auth.method = "token"
auth.token = "123456789"

webServer.addr = "your_addr"
webServer.port = 7500
webServer.user = "admin"
webServer.password = "123456789"

log.to = "./frps.log"
# trace, debug, info, warn, error
log.level = "debug"
log.maxDays = 3

tls.force = false

[[proxies]]
name = "your_home_assistant_proxy_name"
type = "http"
localPort = 8123
customDomains = ["example.com"]
httpUser = "http_user" 
httpPassword = "http_password"

allowPorts = [
  { single = 8123 },
  { single = 7500 },
  { single = 7000 }
]
